/*
 * Copyright (c) 2026 Ivan Tugay
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Generated by cbindgen from crates/ketch-capi/src/abi.rs:
 * `KETCH_BLESS=1 cargo nextest run -p ketch-capi`. Do not edit.
 */

#ifndef KETCH_H
#define KETCH_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// A flag the caller keeps and the calls it is passed to check; trip it with
// `ketch_cancel_cancel` from any thread.
typedef struct KetchCancel KetchCancel;

// A ketch root opened for calls.
typedef struct KetchCore KetchCore;

// Receives each progress event of a call as JSON, an `Event`. NULL: no
// reporting.
typedef void (*KetchEventFn)(const char *event, void *user_data);

// Picks which of several binaries sharing a package's name to link:
// `candidates` is a JSON array of strings; answer an index into it, or a
// negative number to leave it to the fixed rules. NULL: never asked.
typedef int64_t (*KetchChooseFn)(const char *package, const char *candidates, void *user_data);

// Whether to stop the processes that hold files about to be replaced:
// `holders` is a JSON array of `Holder`. `false` leaves them running. NULL:
// always `false`.
typedef bool (*KetchStopFn)(const char *holders, void *user_data);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The version of ketch this library was built from. `ok`: a string.
char *ketch_version(void);

// Free an answer from any function in this library. NULL is ignored.
//
// # Safety
//
// `answer` is NULL or a string this library returned, not yet freed.
void ketch_string_free(char *answer);

// Open the ketch root `root`, or the default root (`KETCH_ROOT`, else
// `~/.ketch`) when NULL. Nothing is read until the first call. NULL when
// `root` is not UTF-8.
//
// # Safety
//
// `root` is NULL or a NUL-terminated string.
struct KetchCore *ketch_core_new(const char *root);

// Close a root opened with `ketch_core_new`. NULL is ignored.
//
// # Safety
//
// `core` came from `ketch_core_new`, is not freed yet, and no call is using it.
void ketch_core_free(struct KetchCore *core);

// A new cancellation flag, not tripped.
struct KetchCancel *ketch_cancel_new(void);

// Trip `cancel`: every call holding it stops at its next check and answers
// `cancelled`. Safe from any thread.
//
// # Safety
//
// `cancel` came from `ketch_cancel_new` and is not freed yet.
void ketch_cancel_cancel(const struct KetchCancel *cancel);

// Whether `cancel` has been tripped. NULL is never tripped.
//
// # Safety
//
// As `ketch_cancel_cancel`.
bool ketch_cancel_is_cancelled(const struct KetchCancel *cancel);

// Free a flag from `ketch_cancel_new`. NULL is ignored.
//
// # Safety
//
// `cancel` came from `ketch_cancel_new`, is not freed yet, and no call is
// using it.
void ketch_cancel_free(struct KetchCancel *cancel);

// The root this core works in. `ok`: a string.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_root(const struct KetchCore *core);

// Every installed package, by name. `ok`: an array of `Package`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_installed(const struct KetchCore *core);

// Packages and repositories matching `query`, at most `limit` repositories.
// `ok`: a `SearchResults`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_search(const struct KetchCore *core,
                   const char *query,
                   uint32_t limit,
                   KetchEventFn event,
                   void *event_data);

// Installed packages with a newer release, pinned ones marked.
// `ok`: an array of `Upgrade`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_outdated(const struct KetchCore *core, KetchEventFn event, void *event_data);

// Install `specs`. `options` is a JSON `InstallOptions`, any field left out
// at its default, or NULL for all defaults. `ok`: an array of `Installed`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_install(const struct KetchCore *core,
                    const char *const *specs,
                    size_t specs_len,
                    const char *options,
                    KetchEventFn event,
                    void *event_data,
                    KetchChooseFn choose,
                    void *choose_data,
                    KetchStopFn stop,
                    void *stop_data,
                    const struct KetchCancel *cancel_token);

// Upgrade `names`, or every package with a newer release when empty; pinned
// packages are skipped. `ok`: an array of `Installed`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_upgrade(const struct KetchCore *core,
                    const char *const *names,
                    size_t names_len,
                    KetchEventFn event,
                    void *event_data,
                    KetchChooseFn choose,
                    void *choose_data,
                    KetchStopFn stop,
                    void *stop_data,
                    const struct KetchCancel *cancel_token);

// Uninstall `names`. `ok`: an array of the `Package`s removed.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_uninstall(const struct KetchCore *core,
                      const char *const *names,
                      size_t names_len,
                      KetchEventFn event,
                      void *event_data,
                      KetchChooseFn choose,
                      void *choose_data,
                      KetchStopFn stop,
                      void *stop_data,
                      const struct KetchCancel *cancel_token);

// What changed in `package` at `version`, or at its newest release when
// NULL. `ok`: a `Changelog`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_changelog(const struct KetchCore *core,
                      const char *package,
                      const char *version,
                      KetchEventFn event,
                      void *event_data);

// The release notes after `from` (NULL: the installed version) up to and
// including `to` (NULL: the newest), newest first. `ok`: an array of
// `Changelog`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_changelog_range(const struct KetchCore *core,
                            const char *package,
                            const char *from,
                            const char *to,
                            KetchEventFn event,
                            void *event_data);

// `ketch doctor`'s checks. `ok`: an array of `Check`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_doctor(const struct KetchCore *core, KetchEventFn event, void *event_data);

// `ketch doctor --fix`: put the bin dir on `PATH` for the shells in use.
// `ok`: an array of `PathChange`, empty when nothing needed fixing.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_doctor_fix(const struct KetchCore *core, KetchEventFn event, void *event_data);

// The newest `limit` events from `stats.db`, for `package` or for all when
// NULL. `ok`: an array of `HistoryEvent`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_history(const struct KetchCore *core, const char *package, uint32_t limit);

// `ketch info`. `ok`: a `PackageInfo`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_info(const struct KetchCore *core,
                 const char *package,
                 KetchEventFn event,
                 void *event_data);

// Pin `names`, or every installed package when empty. `ok`: an array of
// `Package`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_pin(const struct KetchCore *core, const char *const *names, size_t names_len);

// Unpin `names`, or every installed package when empty. `ok`: an array of
// `Package`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_unpin(const struct KetchCore *core, const char *const *names, size_t names_len);

// Go back to the retained version `to`, or the newest retained one when
// NULL. `ok`: an `Installed`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_rollback(const struct KetchCore *core,
                     const char *package,
                     const char *to,
                     KetchEventFn event,
                     void *event_data,
                     KetchChooseFn choose,
                     void *choose_data,
                     KetchStopFn stop,
                     void *stop_data);

// Remove retained versions of `names` (every package when empty) beyond
// `keep`, which also becomes the retention setting; a negative `keep` uses
// the setting as it is. `ok`: an array of `Pruned`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_prune(const struct KetchCore *core,
                  const char *const *names,
                  size_t names_len,
                  int64_t keep,
                  KetchEventFn event,
                  void *event_data);

// Fetch the package registry again. `ok`: the number of packages in it.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_registry_refresh(const struct KetchCore *core, KetchEventFn event, void *event_data);

// Whether the bin dir is on `PATH`, and each shell's setup. `ok`: a
// `PathStatus`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_path_status(const struct KetchCore *core);

// `ketch path install`; with `dry_run`, only what it would change.
// `ok`: an array of `PathChange`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_path_install(const struct KetchCore *core,
                         bool dry_run,
                         KetchEventFn event,
                         void *event_data);

// The settings in effect for this root. `ok`: a `Settings`.
//
// # Safety
//
// The calling rules at the top of ketch-capi's `src/lib.rs`.
char *ketch_config(const struct KetchCore *core);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* KETCH_H */
