// Copyright (c) 2026 Ivan Tugay
// SPDX-License-Identifier: GPL-3.0-or-later
// Licensed under GPL-3.0 or later; see https://www.gnu.org/licenses/gpl-3.0.html

// Generates every derived copy of the design tokens from tokens.json:
//
//   generated/Tokens.swift     SwiftUI constants the macOS app uses instead of
//                              literals (every token)
//   generated/KetchTokens.xaml the Windows app's ResourceDictionary, with Light,
//                              Dark and HighContrast theme dictionaries (brand
//                              tokens only; HighContrast references the user's
//                              SystemColor* contrast-theme palette, no hex)
//   generated/ketch-tokens.css the Linux app's GTK stylesheet, which sets
//                              libadwaita's CSS variables (brand tokens only)
//   preview.html            the CSS variables and token index between its
//                           BEGIN/END GENERATED TOKENS markers
//   ../macos/DESIGN.md      the YAML front matter only; the prose is hand-written
//
// Style Dictionary reads, merges and reference-checks tokens.json and writes the
// files; the formats are ours because its built-in iOS formats emit one static
// colour per token (no light/dark), and its DTCG 2025.10 support is incomplete
// (https://styledictionary.com/info/dtcg/, checked 2026-10-01), so the value
// shapes are parsed in lib.mjs.
//
// Appearance modes live in `$extensions["com.github.pyrlyn.ketch"]` on a token:
// `dark`, `highContrast`, `highContrastDark`. A missing mode falls back:
// highContrastDark -> dark -> light, highContrast -> light. A reference such as
// `{color.accent.default}` resolves in the same mode it is read in.
//
// Only brand tokens leave macOS (BRAND below): Windows and Linux keep their own
// surfaces, so glass, wash, elevation, blur and the macOS layout sizes stay in
// Swift, the preview and DESIGN.md.
//
// Run with `just design-tokens`. Output is deterministic: no dates, no absolute
// paths, keys in source order.

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import StyleDictionary from "style-dictionary";
import {
  MODES, REF, indexTokens, modeValue, ms, num, px, rgba, shadowLayers, toHex, toHex8, byte,
} from "./lib.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const HEADER_LINES = [
  "Generated by desktop/design/build.mjs from desktop/design/tokens.json.",
  "Do not edit: change tokens.json and run `just design-tokens`.",
];

// Token paths that travel to Windows and Linux. A path prefix, matched whole
// segment by segment, so `color.accent` does not catch `color.accentFoo`.
const BRAND = ["color.accent", "color.status", "space", "radius", "typography"];

const brandTokens = (allTokens) =>
  allTokens.filter((t) => {
    const p = t.path.join(".");
    return BRAND.some((b) => p === b || p.startsWith(b + "."));
  });

// --------------------------------------------------------------------- Swift

const SWIFT_KEYWORDS = new Set([
  "default", "case", "class", "enum", "extension", "func", "import", "init", "let", "var",
  "protocol", "static", "struct", "subscript", "switch", "where", "while", "in", "is", "as",
  "self", "Self", "super", "true", "false", "nil", "return", "repeat", "operator", "internal",
  "private", "public", "fileprivate", "open", "do", "else", "for", "if", "guard", "defer",
]);
// Top-level groups renamed where the natural name would shadow a SwiftUI type
// inside `Tokens`.
const SWIFT_GROUP = { color: "Colors", typography: "Typography", motion: "Motion" };

const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const ident = (s) => (SWIFT_KEYWORDS.has(s) ? "`" + s + "`" : s);

function swiftRGBA(c) {
  return `.init(${num(c.r)}, ${num(c.g)}, ${num(c.b)}, ${num(c.a)})`;
}

function swiftDynamic(colors) {
  const [l, d, h, hd] = colors;
  if (colors.every((c) => toHex8(c) === toHex8(l))) return `Color(ketch: ${swiftRGBA(l)})`;
  return `Color(\n  light: ${swiftRGBA(l)},\n  dark: ${swiftRGBA(d)},\n  highContrast: ${swiftRGBA(h)},\n  highContrastDark: ${swiftRGBA(hd)}\n)`;
}

const FONT_WEIGHT = {
  100: ".ultraLight", 200: ".thin", 300: ".light", 400: ".regular", 500: ".medium",
  600: ".semibold", 700: ".bold", 800: ".heavy", 900: ".black",
};

function swiftValue(byPath, token) {
  const where = token.path.join(".");
  const type = token.$type;
  if (type === "color") {
    return {
      type: "Color",
      expr: swiftDynamic(MODES.map((m) => rgba(modeValue(byPath, token, m), `${where} ${m}`))),
    };
  }
  const v = modeValue(byPath, token, "light");
  switch (type) {
    case "dimension":
      return { type: "CGFloat", expr: num(px(v, where)) };
    case "number":
      return { type: "Double", expr: num(v) };
    case "typography": {
      const weight = FONT_WEIGHT[v.fontWeight];
      if (!weight) throw new Error(`${where}: fontWeight ${v.fontWeight} has no SwiftUI weight`);
      const family = Array.isArray(v.fontFamily) ? v.fontFamily[0] : v.fontFamily;
      const design = /mono/i.test(family) ? ".monospaced" : ".default";
      return {
        type: "KetchTypeStyle",
        expr: `KetchTypeStyle(size: ${num(px(v.fontSize, where))}, weight: ${weight}, design: ${design}, lineHeight: ${num(v.lineHeight)}, tracking: ${num(px(v.letterSpacing ?? { value: 0, unit: "px" }, where))})`,
      };
    }
    case "shadow": {
      const layers = shadowLayers(byPath, token);
      if (layers.length === 0) return { type: "[KetchShadow]", expr: "[]" };
      const items = layers.map(
        (l) =>
          `  KetchShadow(\n    color: ${swiftDynamic(l.colors).replace(/\n/g, "\n    ")},\n    x: ${num(l.x)}, y: ${num(l.y)}, blur: ${num(l.blur)}, spread: ${num(l.spread)}, inset: ${l.inset}\n  )`,
      );
      return { type: "[KetchShadow]", expr: `[\n${items.join(",\n")},\n]` };
    }
    case "transition": {
      const c = v.timingFunction;
      return {
        type: "KetchMotion",
        expr: `KetchMotion(duration: ${num(ms(v.duration, where) / 1000)}, curve: (${c.map(num).join(", ")}))`,
      };
    }
    default:
      throw new Error(`${where}: no Swift mapping for $type ${type}`);
  }
}

/** Nested group tree of tokens, in source order. */
function tree(allTokens) {
  const root = { groups: new Map(), tokens: [] };
  for (const t of allTokens) {
    let node = root;
    for (const seg of t.path.slice(0, -1)) {
      if (!node.groups.has(seg)) node.groups.set(seg, { groups: new Map(), tokens: [] });
      node = node.groups.get(seg);
    }
    node.tokens.push(t);
  }
  return root;
}

const SWIFT_PRELUDE = `import AppKit
import SwiftUI

/// Design tokens for ketch on macOS. See desktop/macos/DESIGN.md for how to use them.
public enum Tokens {}

/// A text style: SF Pro at a fixed size, with the line height and tracking the
/// design asks for.
public struct KetchTypeStyle: Sendable {
  public let size: CGFloat
  public let weight: Font.Weight
  public let design: Font.Design
  /// Line height as a multiple of \`size\`.
  public let lineHeight: CGFloat
  /// Letter spacing in points.
  public let tracking: CGFloat

  public var font: Font { .system(size: size, weight: weight, design: design) }
  /// Extra space between lines for \`.lineSpacing(_:)\`.
  public var lineSpacing: CGFloat { size * (lineHeight - 1) }
}

/// One shadow layer. Inset layers are the rim light and shade of the 3D edge;
/// draw them with \`ShadowStyle.inner\`, the rest with \`.shadow(color:radius:x:y:)\`.
public struct KetchShadow: Sendable {
  public let color: Color
  public let x: CGFloat
  public let y: CGFloat
  /// CSS-style blur; SwiftUI's shadow radius is half of it.
  public let blur: CGFloat
  public let spread: CGFloat
  public let inset: Bool

  public var radius: CGFloat { blur / 2 }
}

/// A duration and a cubic-bezier curve.
public struct KetchMotion: Sendable {
  public let duration: TimeInterval
  public let curve: (Double, Double, Double, Double)

  public var animation: Animation {
    .timingCurve(curve.0, curve.1, curve.2, curve.3, duration: duration)
  }
}

/// An sRGB component tuple, 0...1.
public struct KetchRGBA: Sendable {
  let r: CGFloat, g: CGFloat, b: CGFloat, a: CGFloat
  init(_ r: CGFloat, _ g: CGFloat, _ b: CGFloat, _ a: CGFloat) {
    self.r = r; self.g = g; self.b = b; self.a = a
  }
  var nsColor: NSColor { NSColor(srgbRed: r, green: g, blue: b, alpha: a) }
}

extension Color {
  /// One colour in every appearance.
  init(ketch c: KetchRGBA) {
    self.init(nsColor: c.nsColor)
  }

  /// A colour that follows the appearance without an asset catalog: AppKit asks
  /// the provider again whenever the effective appearance changes, including
  /// the high-contrast ones Increase Contrast selects.
  init(light: KetchRGBA, dark: KetchRGBA, highContrast: KetchRGBA, highContrastDark: KetchRGBA) {
    let l = light.nsColor, d = dark.nsColor, h = highContrast.nsColor, hd = highContrastDark.nsColor
    self.init(nsColor: NSColor(name: nil) { appearance in
      switch appearance.bestMatch(from: [
        .aqua, .darkAqua, .accessibilityHighContrastAqua, .accessibilityHighContrastDarkAqua,
      ]) {
      case .darkAqua?: d
      case .accessibilityHighContrastAqua?: h
      case .accessibilityHighContrastDarkAqua?: hd
      default: l
      }
    })
  }
}
`;

function swiftDoc(desc, indent) {
  if (!desc) return "";
  return desc.split("\n").map((l) => `${indent}/// ${l}`).join("\n") + "\n";
}

function swiftGroup(byPath, name, node, indent, source) {
  const inner = indent + "  ";
  let out = swiftDoc(source?.$description, indent);
  out += `${indent}public enum ${name} {\n`;
  const parts = [];
  for (const t of node.tokens) {
    const { type, expr } = swiftValue(byPath, t);
    const e = expr.replace(/\n/g, "\n" + inner);
    parts.push(`${swiftDoc(t.$description ?? t.original.$description, inner)}${inner}public static let ${ident(t.path.at(-1))}: ${type} = ${e}`);
  }
  for (const [seg, child] of node.groups) {
    parts.push(swiftGroup(byPath, pascal(seg), child, inner, source?.[seg]).trimEnd());
  }
  out += parts.join("\n\n") + `\n${indent}}\n`;
  return out;
}

function formatSwift({ dictionary, sourceTree }) {
  const byPath = indexTokens(dictionary.allTokens);
  const root = tree(dictionary.allTokens);
  const groups = [...root.groups].map(([seg, node]) =>
    swiftGroup(byPath, SWIFT_GROUP[seg] ?? pascal(seg), node, "  ", sourceTree[seg]).trimEnd(),
  );
  return (
    HEADER_LINES.map((l) => `// ${l}`).join("\n") +
    "\n\n" +
    SWIFT_PRELUDE +
    "\nextension Tokens {\n" +
    groups.join("\n\n") +
    "\n}\n"
  );
}

// ----------------------------------------------------------------------- CSS

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const cssVar = (path) => "--" + path.map(kebab).join("-");

function cssColor(c) {
  if (c.a === 1) return toHex(c);
  return `rgb(${byte(c.r)} ${byte(c.g)} ${byte(c.b)} / ${num(c.a)})`;
}

const cssFamily = (f) =>
  (Array.isArray(f) ? f : [f]).map((x) => (/^[\w-]+$/.test(x) ? x : `"${x}"`)).join(", ");

/** CSS declarations for `token` in `mode`, as [name, value] pairs. */
function cssDecls(byPath, token, mode) {
  const where = token.path.join(".");
  const name = cssVar(token.path);
  const v = modeValue(byPath, token, mode);
  switch (token.$type) {
    case "color":
      return [[name, cssColor(rgba(v, where))]];
    case "dimension":
      return [[name, `${num(px(v, where))}px`]];
    case "number":
      return [[name, num(v)]];
    case "typography":
      return [
        [name, `${v.fontWeight} ${num(px(v.fontSize, where))}px/${num(v.lineHeight)} ${cssFamily(v.fontFamily)}`],
        [`${name}-tracking`, `${num(px(v.letterSpacing ?? { value: 0, unit: "px" }, where))}px`],
      ];
    case "shadow": {
      const layers = shadowLayers(byPath, token);
      const i = MODES.indexOf(mode);
      const value = layers.length
        ? layers
            .map((l) => `${l.inset ? "inset " : ""}${num(l.x)}px ${num(l.y)}px ${num(l.blur)}px ${num(l.spread)}px ${cssColor(l.colors[i])}`)
            .join(", ")
        : "none";
      return [[name, value]];
    }
    case "transition": {
      const c = v.timingFunction.map(num).join(", ");
      return [
        [name, `${num(ms(v.duration, where))}ms cubic-bezier(${c})`],
        [`${name}-duration`, `${num(ms(v.duration, where))}ms`],
        [`${name}-easing`, `cubic-bezier(${c})`],
      ];
    }
    default:
      throw new Error(`${where}: no CSS mapping for $type ${token.$type}`);
  }
}

function formatCss({ dictionary }) {
  const byPath = indexTokens(dictionary.allTokens);
  const decls = Object.fromEntries(
    MODES.map((m) => [m, dictionary.allTokens.flatMap((t) => cssDecls(byPath, t, m))]),
  );
  const lightMap = new Map(decls.light);
  const block = (sel, pairs, indent = "") =>
    `${indent}${sel} {\n${pairs.map(([k, v]) => `${indent}  ${k}: ${v};`).join("\n")}\n${indent}}\n`;
  // Only what differs from light is repeated in the other modes.
  const diff = (m) => decls[m].filter(([k, v]) => lightMap.get(k) !== v);
  return (
    `/*\n${HEADER_LINES.map((l) => ` * ${l}`).join("\n")}\n *\n` +
    ` * Scope a theme with data-theme="light|dark" and data-contrast="more" on any\n` +
    ` * element; without an attribute the page follows prefers-color-scheme.\n */\n\n` +
    block(':root,\n[data-theme="light"]', decls.light) +
    "\n@media (prefers-color-scheme: dark) {\n" +
    block(":root:not([data-theme])", diff("dark"), "  ") +
    "}\n\n" +
    block('[data-theme="dark"]', diff("dark")) +
    "\n" +
    block('[data-theme="light"][data-contrast="more"]', diff("highContrast")) +
    "\n" +
    block('[data-theme="dark"][data-contrast="more"]', diff("highContrastDark"))
  );
}


// ---------------------------------------------------------------------- XAML

const xmlEscape = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/"/g, "&quot;");

/** `color.accent.default` -> `KetchColorAccentDefault`. */
const xamlKey = (path) => "Ketch" + path.map(pascal).join("");

/** XAML colours are #AARRGGBB, alpha first. */
const xamlColor = (c) => "#" + byte(c.a).toString(16).padStart(2, "0").toUpperCase() + toHex(c).slice(1).toUpperCase();

const XAML_WEIGHT = {
  100: "Thin", 200: "ExtraLight", 300: "Light", 400: "Normal", 500: "Medium",
  600: "SemiBold", 700: "Bold", 800: "ExtraBold", 900: "Black",
};

// The XAML theme key for each appearance. Windows has no dark high-contrast
// theme: a contrast theme is the user's own palette (Aquatic, Desert, Dusk and
// Night sky, three of them dark), so no hex value can be right under all four.
// The `highContrast` mode in tokens.json is macOS Increase Contrast ink for a
// light background and never reaches XAML; HighContrast below holds references
// to the system colours instead.
const XAML_THEMES = [["Light", "light"], ["Dark", "dark"]];

// Windows' own rule for a contrast theme, from the pairings on
// https://learn.microsoft.com/en-us/windows/apps/design/accessibility/high-contrast-themes
// (checked 2026-10-03): Window/WindowText for page, pane and popup backgrounds
// and for headings, body text, borders and other non-interactive UI;
// Highlight/HighlightText for selected or interacted UI; ButtonFace/ButtonText
// for buttons. Hotlight is for hyperlinks and GrayText for disabled UI only, so
// no brand token maps to either. A token with no row here fails the build, so a
// new colour has to pick its system pair on purpose.
const XAML_HIGH_CONTRAST = {
  "color.accent.default": "Highlight",
  "color.accent.pressed": "Highlight",
  "color.accent.on": "HighlightText",
  "color.accent.subtle": "Window",
  "color.accent.ink": "WindowText",
  "color.status.installed": "WindowText",
  "color.status.update": "WindowText",
  "color.status.busy": "WindowText",
  "color.status.warning": "WindowText",
  "color.status.error": "WindowText",
  "color.status.installedSubtle": "Window",
  "color.status.updateSubtle": "Window",
  "color.status.busySubtle": "Window",
  "color.status.warningSubtle": "Window",
  "color.status.errorSubtle": "Window",
};

function formatXaml({ dictionary }) {
  const tokens = brandTokens(dictionary.allTokens);
  const byPath = indexTokens(dictionary.allTokens);
  const entry = (tag, key, value, indent) => `${indent}<${tag} x:Key="${key}">${value}</${tag}>`;
  const brush = (key, c, indent) => `${indent}<SolidColorBrush x:Key="${key}Brush" Color="${c}" />`;

  const themed = XAML_THEMES.map(([theme, mode]) => {
    const lines = [];
    for (const t of tokens.filter((x) => x.$type === "color")) {
      const key = xamlKey(t.path);
      const c = xamlColor(rgba(modeValue(byPath, t, mode), `${t.path.join(".")} ${mode}`));
      lines.push(entry("Color", key, c, "      "), brush(key, c, "      "));
    }
    return `    <ResourceDictionary x:Key="${theme}">\n${lines.join("\n")}\n    </ResourceDictionary>`;
  });

  // The brush follows the docs' own pattern: a SolidColorBrush whose Color is a
  // ThemeResource of the system colour, so it tracks a contrast theme switched
  // while the app runs. The Color entry aliases the same system resource.
  const highContrast = [];
  for (const t of tokens.filter((x) => x.$type === "color")) {
    const where = t.path.join(".");
    const system = XAML_HIGH_CONTRAST[where];
    if (!system) throw new Error(`${where}: no system colour for XAML HighContrast`);
    const key = xamlKey(t.path);
    highContrast.push(
      `      <StaticResource x:Key="${key}" ResourceKey="SystemColor${system}Color" />`,
      `      <SolidColorBrush x:Key="${key}Brush" Color="{ThemeResource SystemColor${system}Color}" />`,
    );
  }
  themed.push(`    <ResourceDictionary x:Key="HighContrast">\n${highContrast.join("\n")}\n    </ResourceDictionary>`);

  // Not themed: spacing, radii and the type scale are the same in every theme.
  const plain = [];
  for (const t of tokens) {
    const where = t.path.join(".");
    const key = xamlKey(t.path);
    const v = modeValue(byPath, t, "light");
    if (t.$type === "color") continue;
    if (t.$type === "dimension" && t.path[0] === "radius") {
      plain.push(entry("CornerRadius", key, num(px(v, where)), "  "));
    } else if (t.$type === "dimension") {
      plain.push(entry("x:Double", key, num(px(v, where)), "  "));
    } else if (t.$type === "typography") {
      const weight = XAML_WEIGHT[v.fontWeight];
      if (!weight) throw new Error(`${where}: fontWeight ${v.fontWeight} has no XAML FontWeight`);
      const size = px(v.fontSize, where);
      plain.push(
        entry("x:Double", `${key}FontSize`, num(size), "  "),
        entry("FontWeight", `${key}FontWeight`, weight, "  "),
        // XAML's LineHeight is in pixels, not a multiple of the size.
        entry("x:Double", `${key}LineHeight`, num(size * v.lineHeight), "  "),
        entry("x:Double", `${key}Spacing`, num(px(v.letterSpacing ?? { value: 0, unit: "px" }, where)), "  "),
      );
    } else {
      throw new Error(`${where}: no XAML mapping for $type ${t.$type}`);
    }
  }
  return (
    `<?xml version="1.0" encoding="utf-8"?>\n<!--\n${HEADER_LINES.map((l) => `  ${xmlEscape(l)}`).join("\n")}\n` +
    `  Brand tokens only (accent, status colours, spacing, radii, type scale): glass, wash,\n` +
    `  blur and elevation stay macOS-only. Font families are left to the app's own theme;\n` +
    `  LineHeight and Spacing (letter spacing) are in pixels, as XAML expects.\n` +
    `  HighContrast holds no hex: it references the SystemColor* resources, so the user's\n` +
    `  contrast theme (Aquatic, Desert, Dusk or Night sky) decides every colour.\n-->\n` +
    `<ResourceDictionary\n    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"\n` +
    `    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">\n` +
    `  <ResourceDictionary.ThemeDictionaries>\n${themed.join("\n")}\n  </ResourceDictionary.ThemeDictionaries>\n\n` +
    `${plain.join("\n")}\n</ResourceDictionary>\n`
  );
}

// ----------------------------------------------------------------------- GTK

// libadwaita variables a brand token overrides. Only the accent and the three
// status colours that libadwaita has a text-colour variable for; `update` and
// `busy` have none, so they ride on --ketch-* only. Status fills (-bg-color)
// are left to libadwaita because our solid status colours carry no label
// colour to pair with them.
const ADWAITA = {
  "color.accent.default": ["--accent-bg-color"],
  "color.accent.on": ["--accent-fg-color"],
  "color.accent.ink": ["--accent-color"],
  "color.status.installed": ["--success-color"],
  "color.status.warning": ["--warning-color"],
  "color.status.error": ["--error-color", "--destructive-color"],
};

function formatGtk({ dictionary }) {
  const tokens = brandTokens(dictionary.allTokens);
  const byPath = indexTokens(dictionary.allTokens);
  const decls = Object.fromEntries(
    MODES.map((m) => [
      m,
      tokens.flatMap((t) => {
        const where = t.path.join(".");
        const v = modeValue(byPath, t, m);
        const name = "--ketch-" + cssVar(t.path).slice(2);
        switch (t.$type) {
          case "color": {
            const value = gtkColor(rgba(v, where));
            return [[name, value], ...(ADWAITA[where] ?? []).map((a) => [a, value])];
          }
          case "dimension":
            return [[name, `${num(px(v, where))}px`]];
          case "typography":
            return [
              [`${name}-font-size`, `${num(px(v.fontSize, where))}px`],
              [`${name}-font-weight`, String(v.fontWeight)],
              [`${name}-line-height`, num(v.lineHeight)],
              [`${name}-letter-spacing`, `${num(px(v.letterSpacing ?? { value: 0, unit: "px" }, where))}px`],
            ];
          default:
            throw new Error(`${where}: no GTK mapping for $type ${t.$type}`);
        }
      }),
    ]),
  );
  const light = new Map(decls.light);
  const diff = (m) => decls[m].filter(([k, val]) => light.get(k) !== val);
  const block = (query, pairs) =>
    `@media ${query} {\n  :root {\n${pairs.map(([k, val]) => `    ${k}: ${val};`).join("\n")}\n  }\n}\n`;
  return (
    `/*\n${HEADER_LINES.map((l) => ` * ${l}`).join("\n")}\n *\n` +
    ` * Brand tokens only (accent, status colours, spacing, radii, type scale): glass, wash,\n` +
    ` * blur and elevation stay macOS-only. Load it as the application's stylesheet at\n` +
    ` * GTK_STYLE_PROVIDER_PRIORITY_APPLICATION. Dark and high-contrast values use\n` +
    ` * @media (prefers-color-scheme) and (prefers-contrast), which AdwApplication's\n` +
    ` * autoloaded styles support from libadwaita 1.8 (GTK 4.20).\n */\n\n` +
    `:root {\n${decls.light.map(([k, val]) => `  ${k}: ${val};`).join("\n")}\n}\n\n` +
    block("(prefers-color-scheme: dark)", diff("dark")) +
    "\n" +
    block("(prefers-contrast: more)", diff("highContrast")) +
    "\n" +
    block("(prefers-color-scheme: dark) and (prefers-contrast: more)", diff("highContrastDark"))
  );
}

const gtkColor = (c) => (c.a === 1 ? toHex(c) : `rgba(${byte(c.r)}, ${byte(c.g)}, ${byte(c.b)}, ${num(c.a)})`);

// ------------------------------------------------------------- DESIGN.md YAML

/** Flat DESIGN.md colour name: `color.accent.default` -> `accent`. */
function designColorName(path) {
  const rest = path.slice(1).filter((s) => s !== "default");
  return rest.map(kebab).join("-");
}

const yamlStr = (s) => JSON.stringify(s);

function formatDesignMd({ dictionary }) {
  const byPath = indexTokens(dictionary.allTokens);
  const of = (group) => dictionary.allTokens.filter((t) => t.path[0] === group && t.path.length > 1);
  const lines = [
    ...HEADER_LINES.map((l) => `# ${l}`),
    "# Light values under their names; dark ones carry a -dark suffix. High-contrast",
    "# values and elevation, blur and motion are in tokens.json only: the DESIGN.md",
    "# schema has no place for them.",
    "version: alpha",
    "name: ketch for macOS",
    `description: ${yamlStr("Liquid Glass package manager: clear glass over a soft ocean wash, one Blue accent, clear status colours.")}`,
    "colors:",
  ];
  const colorTokens = of("color");
  const accent = byPath.get("color.accent.default");
  lines.push(`  primary: ${yamlStr(toHex8(rgba(modeValue(byPath, accent, "light"), "primary")))}`);
  for (const mode of ["light", "dark"]) {
    for (const t of colorTokens) {
      const name = designColorName(t.path) + (mode === "dark" ? "-dark" : "");
      lines.push(`  ${name}: ${yamlStr(toHex8(rgba(modeValue(byPath, t, mode), t.path.join("."))))}`);
    }
  }
  lines.push("typography:");
  for (const t of of("typography")) {
    const v = modeValue(byPath, t, "light");
    const fam = Array.isArray(v.fontFamily) ? v.fontFamily[0] : v.fontFamily;
    lines.push(
      `  ${kebab(t.path[1])}:`,
      `    fontFamily: ${yamlStr(fam)}`,
      `    fontSize: ${num(px(v.fontSize, t.name))}px`,
      `    fontWeight: ${v.fontWeight}`,
      `    lineHeight: ${num(v.lineHeight)}`,
      `    letterSpacing: ${num(px(v.letterSpacing ?? { value: 0, unit: "px" }, t.name))}px`,
    );
  }
  lines.push("rounded:");
  for (const t of of("radius")) lines.push(`  ${kebab(t.path[1])}: ${num(px(t.$value, t.name))}px`);
  lines.push("spacing:");
  for (const t of of("space")) lines.push(`  ${kebab(t.path[1])}: ${num(px(t.$value, t.name))}px`);
  lines.push("components:");
  const components = new Map();
  for (const t of of("component")) {
    const key = kebab(t.path[1]);
    if (!components.has(key)) components.set(key, []);
    components.get(key).push(t);
  }
  const section = { color: "colors", radius: "rounded", space: "spacing", typography: "typography" };
  for (const [key, props] of components) {
    lines.push(`  ${key}:`);
    for (const t of props) {
      const ref = REF.exec(t.original.$value ?? "");
      let value;
      const target = ref && byPath.get(ref[1]);
      if (target && section[target.path[0]]) {
        const name = target.path[0] === "color" ? designColorName(target.path) : kebab(target.path.at(-1));
        value = yamlStr(`{${section[target.path[0]]}.${name}}`);
      } else if (t.$type === "color") {
        value = yamlStr(toHex8(rgba(modeValue(byPath, t, "light"), t.name)));
      } else {
        value = `${num(px(modeValue(byPath, t, "light"), t.name))}px`;
      }
      lines.push(`    ${t.path[2]}: ${value}`);
    }
  }
  return lines.join("\n") + "\n";
}

// ------------------------------------------------------------- preview index

/** Display string of `token` in `mode`, for the preview's token tables. */
function display(byPath, token, mode) {
  const where = token.path.join(".");
  const v = modeValue(byPath, token, mode);
  switch (token.$type) {
    case "color":
      return toHex8(rgba(v, where));
    case "dimension":
      return `${num(px(v, where))}px`;
    case "typography":
      return `${v.fontWeight} ${num(px(v.fontSize, where))}/${num(v.lineHeight)}`;
    case "shadow":
      return `${shadowLayers(byPath, token).length} layers`;
    case "transition":
      return `${num(ms(v.duration, where))}ms`;
    default:
      return String(v);
  }
}

/** The token list preview.html builds its swatches and tables from. */
function formatIndex({ dictionary }) {
  const byPath = indexTokens(dictionary.allTokens);
  const rows = dictionary.allTokens.map((t) => ({
    path: t.path.join("."),
    var: cssVar(t.path),
    type: t.$type,
    description: t.$description ?? t.original.$description ?? "",
    values: Object.fromEntries(MODES.map((m) => [m, display(byPath, t, m)])),
  }));
  // `<` escaped so a description can never close the script element.
  return JSON.stringify(rows).replace(/</g, "\\u003c");
}

// ---------------------------------------------------------------------- main

const sourceTree = JSON.parse(await readFile(join(here, "tokens.json"), "utf8"));

const sd = new StyleDictionary({
  source: [join(here, "tokens.json")],
  usesDtcg: true,
  log: { verbosity: "silent", warnings: "error" },
  hooks: {
    formats: {
      "ketch/swiftui": (args) => formatSwift({ ...args, sourceTree }),
      "ketch/css": formatCss,
      "ketch/index": formatIndex,
      "ketch/design-md": formatDesignMd,
      "ketch/xaml": formatXaml,
      "ketch/gtk": formatGtk,
    },
  },
  platforms: {
    // One platform builds all three generated files; named for the first, the
    // one the app compiles.
    swift: {
      // Unique names only; our formats read paths, never names.
      transforms: ["name/kebab"],
      buildPath: join(here, "generated") + "/",
      files: [
        { destination: "Tokens.swift", format: "ketch/swiftui" },
        { destination: "KetchTokens.xaml", format: "ketch/xaml" },
        { destination: "ketch-tokens.css", format: "ketch/gtk" },
      ],
    },
    // The next two are spliced into files, not written: formatPlatform only.
    preview: {
      transforms: ["name/kebab"],
      files: [
        { destination: "tokens.css", format: "ketch/css" },
        { destination: "index.json", format: "ketch/index" },
      ],
    },
    designmd: {
      transforms: ["name/kebab"],
      files: [{ destination: "front-matter.yaml", format: "ketch/design-md" }],
    },
  },
});

await sd.buildPlatform("swift");

/** Replace `pattern`'s match in `file` with `replacement`; write only on change. */
async function splice(file, pattern, replacement, what) {
  const text = await readFile(file, "utf8");
  if (!pattern.test(text)) throw new Error(`${file}: ${what} not found`);
  const next = text.replace(pattern, () => replacement);
  if (next !== text) await writeFile(file, next);
}

// DESIGN.md keeps its hand-written prose; only the front matter between the
// first two `---` lines is replaced, so the YAML never becomes a second
// hand-edited copy of tokens.json.
const [{ output: yaml }] = await sd.formatPlatform("designmd");
await splice(
  join(here, "..", "macos", "DESIGN.md"),
  /^---\n(?:[\s\S]*?\n)?---\n/,
  `---\n${yaml}---\n`,
  "a leading --- front matter block",
);

// preview.html stays one self-contained file that opens from disk: the CSS
// variables and the token index go inline between two marker comments.
const preview = await sd.formatPlatform("preview");
const css = preview.find((f) => f.destination === "tokens.css").output;
const index = preview.find((f) => f.destination === "index.json").output;
const BEGIN = "<!-- BEGIN GENERATED TOKENS -->";
const END = "<!-- END GENERATED TOKENS -->";
await splice(
  join(here, "preview.html"),
  new RegExp(`${BEGIN}[\\s\\S]*?${END}`),
  `${BEGIN}\n<!-- ${HEADER_LINES.join(" ")} -->\n<style id="ketch-tokens">\n${css}</style>\n` +
    `<script type="application/json" id="ketch-token-index">${index}</script>\n${END}`,
  "the generated-token markers",
);
