#!/bin/sh
# Copyright (c) 2026 Ivan Tugay
# SPDX-License-Identifier: GPL-3.0-or-later
# Licensed under GPL-3.0 or later; see https://www.gnu.org/licenses/gpl-3.0.html

# The release workflows must parse, and the strings that hold them together
# must stay: the patches scripts/dist-generate.sh makes to the generated
# release.yml, the one entry point that tags and dispatches it (bump.yml), and
# the subject contract between release-plz.toml, release.sh and cliff.toml.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
wf="$ROOT/.github/workflows"

command -v ruby >/dev/null 2>&1 \
    || { echo "release-workflows: ruby is required to parse the workflows" >&2; exit 1; }
for f in release bump tap; do
    [ -f "$wf/$f.yml" ] || { echo "release-workflows: missing $wf/$f.yml" >&2; exit 1; }
    ruby -ryaml -e "YAML.load_file(ARGV[0])" "$wf/$f.yml"
done

need() {
    if ! grep -q -- "$2" "$1"; then
        echo "release-workflows: $(basename "$1") is missing $3" >&2
        exit 1
    fi
}

r="$wf/release.yml"
need "$r" 'autogenerated by dist' 'the dist header (regenerate with `just dist-generate`)'
need "$r" 'CODESIGN_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}' 'the MACOS_CERTIFICATE mapping'
need "$r" 'CODESIGN_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}' 'the MACOS_CERTIFICATE_PWD mapping'
need "$r" 'Discover macOS codesign identity' 'the identity step from .github/build-setup.yml'
need "$r" 'name: Notarise' 'the Notarise step from .github/build-check.yml'
need "$r" "vars.KETCH_NOTARIZE == 'true'" 'the KETCH_NOTARIZE gate'
need "$r" 'secrets.APPSTORE_CONNECT_KEY }}' 'APPSTORE_CONNECT_KEY'
need "$r" 'secrets.APPSTORE_CONNECT_KEY_ID' 'APPSTORE_CONNECT_KEY_ID'
need "$r" 'secrets.APPSTORE_CONNECT_ISSUER_ID' 'APPSTORE_CONNECT_ISSUER_ID'
need "$r" 'xcrun notarytool submit' 'notarytool submit'
need "$r" 'source=Notarized Developer ID' 'the spctl smoke check'
need "$r" 'name: Smoke test' 'the smoke test'
need "$r" 'sha256sum $(ls ketch-\*.tar.gz | sort) > SHA256SUMS' 'the aggregate SHA256SUMS'
need "$r" 'uses: ./.github/workflows/tap.yml' 'the tap publish job'
need "$r" 'pyrlyn/ci/.github/actions/notify-release-failure@' 'the release-failure job'
need "$r" 'gh release upload "${{ needs.plan.outputs.tag }}" artifacts/\*' 'the upload to bump'"'"'s draft (create-release = false)'
if grep -q 'gh release create' "$r"; then
    echo "release-workflows: release.yml creates a release (and a tag); bump.yml does that" >&2
    exit 1
fi
[ ! -f "$wf/release-plz.yml" ] \
    || { echo "release-workflows: release-plz.yml is back; bump.yml is the only release path" >&2; exit 1; }
need "$ROOT/dist-workspace.toml" '^create-release = false' 'create-release = false'
need "$ROOT/release-plz.toml" '^git_tag_enable = false' 'git_tag_enable = false'

b="$wf/bump.yml"
need "$b" 'options: \[patch, minor, major\]' 'the patch/minor/major choice'
need "$b" 'uses: pyrlyn/ci/.github/workflows/bump.yml@' 'the shared bump workflow'
need "$b" 'release-script: scripts/release.sh' 'the release.sh call'
need "$b" 'BUMP_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}' 'the token that gives the bump pull request its CI'
need "$b" 'release-workflows: release.yml' 'the release.yml dispatch'
need "$b" 'issues: write' 'issues: write for the shared notify-failure job'

need "$ROOT/release-plz.toml" 'pr_name = "chore: release v{{ version }}"' 'the version commit subject'
need "$ROOT/release-plz.toml" 'changelog_config = "cliff.toml"' 'the shared git-cliff config'
need "$ROOT/cliff.toml" 'message = "^chore: release v", skip = true' 'the skipped version commit'
need "$ROOT/scripts/release.sh" 'git commit --quiet -m "chore: release v$version"' 'the version commit subject'
